default_language_version:
  python: python3

exclude: "vendor"

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-case-conflict
      - id: check-ast
      - id: check-docstring-first
      - id: check-executables-have-shebangs
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-json
      - id: check-toml
      - id: check-yaml
      - id: debug-statements
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: detect-private-key

  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0.28.6
    hooks:
      - id: check-github-workflows

  - repo: https://github.com/executablebooks/mdformat
    rev: 0.7.17
    hooks:
      - id: mdformat
        additional_dependencies:
          [mdformat-gfm, mdformat-frontmatter, mdformat-footnote]

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v4.0.0-alpha.8"
    hooks:
      - id: prettier
        types_or: [yaml, html, json]

  - repo: https://github.com/codespell-project/codespell
    rev: "v2.3.0"
    hooks:
      - id: codespell
        args: ["-L", "sur,nd"]

  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: "v1.10.0"
    hooks:
      - id: rst-backticks
      - id: rst-directive-colons
      - id: rst-inline-touching-normal

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.5.0
    hooks:
      - id: ruff
        types_or: [python]
        args: ["--fix", "--show-fixes"]
      - id: ruff-format
        types_or: [python, jupyter]

  # python upgrading syntax to newer version
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.3.1
    hooks:
      - id: pyupgrade
        args: [--py38-plus]

  # # python docstring formatting
  # - repo: https://github.com/myint/docformatter
  #   rev: v1.7.4
  #   hooks:
  #     - id: docformatter
  #       args:
  #         [
  #           --in-place,
  #           --wrap-summaries=99,
  #           --wrap-descriptions=99,
  #           --style=sphinx,
  #           --black,
  #         ]

  # # python docstring coverage checking
  # - repo: https://github.com/econchick/interrogate
  #   rev: 1.5.0 # or master if you're bold
  #   hooks:
  #     - id: interrogate
  #       args:
  #         [
  #           --verbose,
  #           --fail-under=80,
  #           --ignore-init-module,
  #           --ignore-init-method,
  #           --ignore-module,
  #           --ignore-nested-functions,
  #           -vv,
  #         ]

  # shell scripts linter
  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.9.0.2
    hooks:
      - id: shellcheck

  # jupyter notebook cell output clearing
  - repo: https://github.com/kynan/nbstripout
    rev: 0.6.1
    hooks:
      - id: nbstripout

  # - repo: https://github.com/RobertCraigie/pyright-python
  #   rev: v1.1.383
  #   hooks:
  #     - id: pyright
