name: manten
channels:
  - pytorch
  - nvidia
  - dglteam/label/th24_cu121
  - conda-forge
dependencies:
  - python=3.10

  - accelerate

  - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda=12.1

  - dgl # requires torch<=2.4.0, but that error's fine

  - pip:
      - hydra-core
      - hydra-colorlog
      - wandb
      - tqdm
      - rootutils

      - diffusers[training]
      - transformers
      - blosc
      - einops
      - optree

      # - pre-commit
      # - ipykernel

      - matplotlib
      - plotly
      - tabulate

      # tdda
      - git+https://github.com/openai/CLIP.git
      - flash-attn
