defaults:
  - _self_
  - optional local: local

agent_proxy:
  _target_: manten_evaluation.agent_proxy_client.AgentProxyClient
  timeout: null

ep_len: 360
num_sequences: 1000
debug: False
num_videos: 0

pcd_as_part_of_obs: True # needed for TDDA

eval_log_dir: ???
dataset_path: ???
calvin_models_dir: ???
