# @package _global_

defaults:
  # - /evaluator: calvin
  - /datamodule: calvin

_relative_action: True

datamodule:
  train_dataloader: null
# can also change num_diffusion_timesteps for agent inference here
# via agent_override, since the agent is taken from train_folder
