_target_: manten.networks.manten_transformer_for_diffusion.MantenTransformer
_partial_: True
depth: 12
depth_encoder: 0
dim: 768
emb_dropout: 0.1
ff_mult: 4

concat_cond_dims_into_one: True

layer_kwargs:
  heads: 8
  attn_dropout: 0.1
  ff_dropout: 0.1
  ff_glu: True
  # ff_swish: True
  attn_flash: True
  pre_norm: True # important for stability???
  # num_memory_tokens: 20
  # use_scalenorm: True
  # post_emb_norm: True
