_target_: manten.networks.transformer.manten_transformer_for_diffusion_v2.MantenTransformerV2
_partial_: True
n_layer: 12
n_cond_layers: ??? # use a simple linear layer to condition the decoder
n_emb: 768
p_drop_emb: 0.1
causal_attn: False
ff_mult: 4

concat_cond_dims_into_one: False

layer_kwargs:
  nhead: 12
  dropout: 0.1
  activation: "gelu"
  batch_first: True
  norm_first: True # important for stability