defaults:
  - _self_
  - hydra: test

  # following are global
  - optional local: local
  - debug: null

agent_wrapper:
  _target_: manten_evaluation.calvin.agent_wrappers.tdda.TDDAAgentWrapper
  text_encoder: clip
  text_max_length: 16 # 53

seed: 142
deterministic: False
device: cuda

testing:
  train_folder: ???
  checkpoint: null
  agent_override: {}

host: "localhost"
port: 12567
