defaults:
  - _self_
  - hydra: test

  # following are global
  - optional local: local
  - debug: null

seed: 142
deterministic: False
device: cuda

testing:
  train_folder: ???
  checkpoint: null
  agent_override: {}

host: "localhost"
port: 12567
