defaults:
  - _self_
  - hydra: test

  # following are global
  - optional local: local
  - debug: null

seed: 142
deterministic: False
device: cuda

testing:
  train_folder: /home/i53/student/yagmurlu/code/manten/outputs/from_horeka/11-53-09/accelerate
  checkpoint: best_checkpoint
  agent_override: {}

host: "localhost"
port: 12567
