defaults:
  - _self_
  - hydra: default

    # following are global
  - experiment_eval: ???
  - debug: null
  # - optional local: local

seed: 542
deterministic: False
device: cuda

agent_creation:
  load_agent_kwargs:
    train_folder: ???
    use_ema: True
  agent_wrapper: ???

evaluator: ???

hydra:
  run:
    dir: ./outputs/unknown-evaluator/${now:%Y-%m-%d}/${now:%H-%M-%S}
