_calvin_ver: task_D_D

_training_calvin_data: ???
_validation_calvin_data: ???
_instructions: ???

_relative_action: ${_relative_action}
_batch_size: 30
_num_workers: 4

datamodule:
  _target_: manten.utils.utils_data.DummyDataModule
  train_dataloader: &_train_dataloader
    _target_: torch.utils.data.DataLoader
    dataset: &_train_dataloader_dataset
      _target_: manten.data.dataset_calvin.CalvinDataset
      root: ${...._training_calvin_data}
      instructions: ${...._instructions}
      max_episode_length: 5000
      cache_size: 0
      max_episodes_per_task: -1
      cameras: [front, wrist]
      training: True
      image_rescale: [0.75, 1.25]
      dense_interpolation: 1
      interpolation_length: 20 # hardcoded max in preprocess
      relative_action: ${...._relative_action}
    collate_fn:
      _target_: manten.data.dataset_calvin.traj_collate_fn
      _partial_: true
    batch_size: ${..._batch_size}
    shuffle: True
    num_workers: ${..._num_workers}
    pin_memory: True
    drop_last: False
  test_dataloader:
    <<: *_train_dataloader
    dataset:
      <<: *_train_dataloader_dataset
      root: ${...._validation_calvin_data}
      training: False
