defaults:
  - metric@agent.metric: combined_2d_3d_mse
  - pred_net@agent.pred_net: manten_transformer_v2
  - encoder@agent.encoder: manten_encoder

agent:
  _target_: manten.agents.combined.manten_policy.manten_combined_policy.MantenCombinedPolicy
  act_horizon: 8
  num_diffusion_iters: 100
  train_modes: ???
  noise_scheduler:
    _target_: diffusers.schedulers.DDPMScheduler
    num_train_timesteps: 100
    beta_schedule: squaredcos_cap_v2
  action_scaler:
    _target_: manten.agents.utils.normalization.MinMaxScaler
    _partial_: true
    min_value: -0.95
    max_value: 0.95