defaults:
  - metric@agent.metric: combined_2d_3d_mse
  - pcd_encoder@agent.pcd_encoder: knn_group_encoder
  # - pcd_encoder@agent.pcd_encoder: pointnext-s

agent:
  _target_: manten.agents.combined_manten_policy.manten_combined_policy.MantenCombinedPolicy
  act_horizon: 8
  num_diffusion_iters: 100
  train_modes: ???
  noise_scheduler:
    _target_: diffusers.schedulers.DDPMScheduler
    num_train_timesteps: 100
    beta_schedule: squaredcos_cap_v2
  action_scaler:
    _target_: manten.agents.utils.normalization.MinMaxScaler
    _partial_: true
    min_value: -0.95
    max_value: 0.95
  pred_net:
    _target_: manten.networks.manten_transformer_for_diffusion.MantenTransformer
    _partial_: True
    dim: 768
    emb_dropout: 0.1
    encoder:
      _target_: manten.networks.manten_transformer_for_diffusion.MantenTransformerWrapper
      _partial_: True
      attn_layers:
        _target_: x_transformers.Encoder
        _partial_: True
        # attn_num_mem_kv: 16
    decoder:
      _target_: manten.networks.manten_transformer_for_diffusion.MantenTransformerWrapper
      _partial_: True
      attn_layers:
        _target_: x_transformers.Decoder
        _partial_: True
    depth: 6
    heads: 8
    # layer_dropout: 0.1 # causes problems with torch distributed
    attn_dropout: 0.1
    ff_dropout: 0.1
    attn_flash: True
    # num_memory_tokens: 20
    use_scalenorm: True
    post_emb_norm: True
    ff_glu: True
    ff_swish: True
  rgb_encoder:
    _target_: manten.networks.vendor.diffusion_policy.vision.multi_image_obs_encoder.MultiImageObsEncoder
    _partial_: True
    rgb_model:
      _target_: manten.networks.vendor.diffusion_policy.vision.model_getter.get_resnet
      name: resnet18
      weights: null
    resize_shape: null
    crop_shape: [76, 76]
    # constant center crop
    random_crop: True
    use_group_norm: True
    share_rgb_model: False
    imagenet_norm: True
