defaults:
  - metric@agent.metric: combined_2d_3d

_diffusion_timesteps: ???
agent:
  _target_: manten.agents.tdda_combined_2d3d.c2d3d_tdda_agent.Combined2D3DTDDAAgent
  position_noise_scheduler:
    _target_: diffusers.schedulers.DDPMScheduler
    num_train_timesteps: ${..._diffusion_timesteps}
    beta_schedule: scaled_linear
    prediction_type: epsilon
  rotation_noise_scheduler:
    _target_: diffusers.schedulers.DDPMScheduler
    num_train_timesteps: ${..._diffusion_timesteps}
    beta_schedule: squaredcos_cap_v2
    prediction_type: epsilon
  encoder:
    _partial_: True
    _target_: manten.networks.vendor.three_dda.encoder.Encoder
    backbone: "clip"
    num_sampling_level: 1
    num_vis_ins_attn_layers: 2
    fps_subsampling_factor: 3
  noise_model:
    _partial_: True
    _target_: manten.networks.vendor.three_dda.head.DiffusionHead
    use_instruction: True
    lang_enhanced: True
  sigmoid_openness_in_inference: True
  relative: ???
  act_horizon: ???
  # use_instruction: True
  n_inference_steps: ${.._diffusion_timesteps}
  embedding_dim: 192
