_diffusion_timesteps: ???
agent:
  _target_: manten.agents.only_3d.td_diffuser_actor.three_dda_agent.ThreeDDAAgent
  position_noise_scheduler:
    _target_: diffusers.schedulers.DDPMScheduler
    num_train_timesteps: ${..._diffusion_timesteps}
    beta_schedule: scaled_linear
    prediction_type: epsilon
  rotation_noise_scheduler:
    _target_: diffusers.schedulers.DDPMScheduler
    num_train_timesteps: ${..._diffusion_timesteps}
    beta_schedule: squaredcos_cap_v2
    prediction_type: epsilon
  encoder:
    _partial_: True
    _target_: manten.networks.vendor.three_dda.encoder.Encoder
    backbone: "clip"
    num_sampling_level: 1
    num_vis_ins_attn_layers: 2
    fps_subsampling_factor: 3
  noise_model:
    _partial_: True
    _target_: manten.networks.vendor.three_dda.head.DiffusionHead
    use_instruction: True
    lang_enhanced: True
  sigmoid_openness_in_inference: True
  metric:
    _target_: manten.metrics.mse_loss_pose_bce_loss_gripper_metric.MSELossPoseBCEWithLogitsLossGripperMetric
    pos_weight: 10.0
    rot_weight: 5.0
    gripper_weight: 1.0
  relative: ???
  act_horizon: ???
  # use_instruction: True
  n_inference_steps: ${.._diffusion_timesteps}
  embedding_dim: 192
