# @package _global_

task_name: "debug"

debug: # order matters here
  _target_: manten.utils.debug_utils.DebugUtils
  # env_set:
  #   # this is not working via hydra, set manually in shell if you have problems
  #   TORCH_DISTRIBUTED_DEBUG: DETAIL
  #   ACCELERATE_DEBUG_MODE: 1
  monkeypatch_tensor_shape: True

accelerator_init_trackers:
  project_name: ${project_name}_debug
# hydra:
# # sets level of all command line loggers to 'DEBUG'
# # https://hydra.cc/docs/tutorials/basic/running_your_app/logging/
#   job_logging:
#     root:
#       level: DEBUG
