# @package _global_

defaults:
  - common

training:
  num_epochs: 3
  max_steps: 3
  sanity_check: 2
  validate_ene_max_steps: 3
  eval_train_ene_max_steps: 3
  eval_test_ene_max_steps: 3

  validate_every_n_epochs: 1
  eval_train_every_n_epochs: 1
  eval_test_every_n_epochs: 1

  save_every_n_epochs: 0
  log_every_n_steps: 1
