# @package _global_

defaults:
  - common

training:
  num_epochs: 3
  num_global_steps: .inf
  max_steps: 3
  sanity_check: 2
  # epoch settings override global_steps so following is fine
  val:
    every_n_epochs: 1
    skip_first_epochs: 0
    max_steps: 2
  eval_train:
    every_n_epochs: 1
    skip_first_epochs: 0
    max_steps: 2
  eval_test:
    every_n_epochs: 1
    skip_first_epochs: 0
    max_steps: 2
  custom_eval:
    every_n_epochs: 3
    skip_first_epochs: 0
  save:
    every_n_epochs: 3
    skip_first_epochs: 0

  log_every_n_steps: 1
