_target_: manten.networks.utils.openpoints_model.OpenPointsModel
_partial_: True
model:
  _target_: manten.networks.vendor.openpoints.backbone.pointnext.PointNextEncoder
  blocks: [1, 1, 1, 1, 1]
  strides: [1, 2, 4, 2, 2]
  sa_layers: 3
  sa_use_res: False
  width: 4
  # in_channels: 7
  in_channels: 3
  expansion: 4
  radius: 0.05
  nsample: 32
  aggr_args:
    feature_type: "dp_fj"
    reduction: "max"
  group_args:
    NAME: "ballquery"
    normalize_dp: True
  conv_args:
    order: conv-norm-act
  act_args:
    act: "relu"
  norm_args:
    norm: "bn"
  forward_routes_to: forward_cls_feat
